### ISSUE TITLE
Error Output "WAIT"

### ISSUE THREAD

**Issue by fabolhak** [lms-org/pause_runtime#1]
In jedem Zyklus wird ein Error ausgegeben:
https://github.com/lms-org/pause_runtime/blob/e54886e38d4f54f2c5ab36dcde40c54baa059afb/src/pause_runtime.cpp#L90

Sollte mich das beunruhigen oder ist das "normal"?

Muss dieses Modul im Normalbetrieb ausgeführt werden oder ist es nur für Debug?

**Comment by Phibedy** [comment]
Das ist eine Debug Ausgabe, müsste man noch auf Debug ändern :)

**Comment by fabolhak** [comment]
ok. Vielen Dank :). Ich kann es leider nicht ändern:
`remote: Permission to lms-org/pause_runtime.git denied to fabolhak.`

**Comment by Phibedy** [comment]
#Pullrequest :)
